# config.yaml

Racing Stradegy:
  variable: strat
  choices:  
    button0: 
      title: racing
    button1: 
      title: Lightning McQueen
    button2: 
      title: Vroom Vroom

Perception:
  variable: eyes
  choices:
    button3: 
      title: Camera
    button4: 
      title: LiDar

Mapping:
  variable: mapper
  choices:
    button5: 
      title: gmap
    button6: 
      title: applemaps
    button7: 
      title: areWeTheirYet

Planning:
  variable: planner
  choices:
    button8: 
      title: calander
    button9: 
      title: planner
