# config.yaml
Version: 2020021 #used to kepp track of diffrent configs and relate to saved profiles

Racing Stradegy: #module name
  variable: strat #varname that gets passed in string
  choices:  #list of buttons and thier values
    Racing_1: #button value passed to the string
      title: Racing #title of the button in the GUI
      dependencies: #list of other choices that
        #button3 for exaple
    Racing_2: 
      title: Lightning McQueen
      dependencies:
    Racing_3: 
      title: Vroom Vroom
      dependencies:
   
Perception:
  variable: eyes
  choices:
    Perception_1: 
      title: Camera
    Perception_2: 
      title: LiDar

Mapping:
  variable: mapper
  choices:
    Mapping_1: 
      title: gmap
    Mapping_2: 
      title: applemaps
    Mapping_3: 
      title: areWeTheirYet

Planning:
  variable: planner
  choices:
    Planning_1: 
      title: calander
    Planning_2: 
      title: planner
