# config.yaml - for creating a configuration window


# used to keep track of different configs and relate to saved profiles
Version: 2020021 

Racing Strategy: #module name
  variable: strat #varname that gets passed in string
  description: This decides how they are going have the car run. 
  choices:  #list of buttons and their values
    Racing_1: #button value passed to the string
      title: Vroom Vroom #title of the button in the GUI
      dependencies: Perception_1, Mapping_1, Planning_1
      description: This is the first racing strategy. 
    Racing_2: 
      title: Lightning McQueen
      dependencies: Perception_2, Mapping_2, Planning_2
      description: This is the second racing strategy. 
    Racing_3: 
      title: Manual Override
      dependencies:
      description: This is the final racing strategy.
   
Perception:
  variable: eyes
  description: This is how the car is going to see. 
  choices:
    Perception_1: 
      title: Camera
      dependencies: Racing_1, Mapping_1, Planning_1
      description: This uses a camera as the visual aid. 
    Perception_2: 
      title: LiDar
      dependencies: Racing_2, Mapping_2, Planning_2
      description: This uses a Lidar as the visual aid. 

Mapping:
  variable: mapper
  description: This is what sets the type of mapping it is going to see. 
  choices:
    Mapping_1: 
      title: gmap
      dependencies: Racing_1, Perception_1, Planning_1
      description: This uses google maps. 
    Mapping_2: 
      title: applemaps
      dependencies: Racing_2, Perception_2, Planning_2
      description: This uses apple maps.
    Mapping_3: 
      title: areWeTheirYet
      dependencies: 
      description: This is an example explanation for this value.

Planning:
  variable: planner
  description: This is the algorithm that will allow the car to plan ahead. 
  choices:
    Planning_1: 
      title: calander
      dependencies: Racing_1, Mapping_1, Perception_1
      description: This is an eample explanation for what this does. 
    Planning_2: 
      title: planner
      dependencies: Racing_2, Mapping_2, Perception_2
      description: This is an example for this value. 
