# config.yaml
Version: 20200221 #used to kepp track of diffrent configs and relate to saved profiles

Racing Stradegy: #module name
  variable: strat #varname that gets passed in string
  choices:  #list of buttons and thier values
    button0: #button value passed to the string
      title: racing #title of the button in the GUI
      dependencies: #list of other choices that
        #button3 for exaple
    button1: 
      title: Lightning McQueen
      dependencies:
    button2: 
      title: Vroom Vroom
      dependencies:
   
Perception:
  variable: eyes
  choices:
    button3: 
      title: Camera
    button4: 
      title: LiDar

Mapping:
  variable: mapper
  choices:
    button5: 
      title: gmap
    button6: 
      title: applemaps
    button7: 
      title: areWeTheirYet

Planning:
  variable: planner
  choices:
    button8: 
      title: calander
    button9: 
      title: planner
